plugin: openstack.cloud.openstack
expand_hostvars: true
fail_on_errors: true
inventory_hostname: name
only_ipv4: true
private: true

keyed_groups:
  - prefix: subject
    key: openstack.metadata.subject

groups:
  data_science: openstack.metadata.subject == 'data_science'
  frontend: openstack.metadata.subject == 'frontend'
  databases: openstack.metadata.subject == 'databases'
  backend: openstack.metadata.subject == 'backend'
  fullstack: openstack.metadata.subject == 'fullstack'
