---
- name: Configuracion para la asignatura de Desarrollo Fullstack
  hosts: fullstack
  become: true
  roles:
    - common
    - security_hardening
    - frontend_tools
    - backend_tools
    - mariadb
