---
- import_playbook: playbooks/data_science.yml
- import_playbook: playbooks/frontend.yml
- import_playbook: playbooks/databases.yml
- import_playbook: playbooks/backend.yml
- import_playbook: playbooks/fullstack.yml
